package com.asatisamaj.matrimony.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class DropDownValues {

	private List<String> getSamajArea = new ArrayList<>();
	private List<String> getEducation = new ArrayList<>();
	private List<String> getEducationDetails = new ArrayList<>();;
	private List<String> getOccupation = new ArrayList<>();
	private List<String> getAgeRange = new ArrayList<>();

	public List<String> getGetSamajArea() {
		getSamajArea.add("Damoh");
		getSamajArea.add("Jabalpur");
		getSamajArea.add("Bhopal");
		getSamajArea.add("Gondia");
		getSamajArea.add("Tikamgarh");
		getSamajArea.add("Chhatarpur");
		getSamajArea.add("Hata");
		getSamajArea.add("Katni");
		getSamajArea.add("Sagar");
		getSamajArea.add("Hirapur-Ghuwar-Badagaon");
		getSamajArea.add("Chhatishgarh ");
		getSamajArea.add("Balaghat");
		getSamajArea.add("Bijawar-Satai");
		getSamajArea.add("Badamalhara");
		getSamajArea.add("Baldevgarh-Khargapur");
		getSamajArea.add("Others");
		getSamajArea.add("Indore");
		getSamajArea.add("Sagar");
		getSamajArea.add("Ghuwara-Badagaon");
		getSamajArea.add("Hirapur-Shahgad");
		Collections.sort(getSamajArea);
		return getSamajArea;
	}

	public List<String> getGetEducationDetails() {
		getEducationDetails.add("Vocational Education Pharma");
		getEducationDetails.add("Graduate");
		getEducationDetails.add("vocational Education Engineering");
		getEducationDetails.add("vocational Education B.Ed");
		getEducationDetails.add("vocational Education Doctor");
		getEducationDetails.add("vocational Education CA");
		getEducationDetails.add("Class 1 to 10");
		getEducationDetails.add("Vocational Education CS");
		getEducationDetails.add("vocational Education D.Ed");
		getEducationDetails.add("Vocational Education Computor");
		getEducationDetails.add("Vocational Education Ploytechnic");
		getEducationDetails.add("Vocational Education ITI");
		getEducationDetails.add("Vocational Education Ploy/ITI");
		getEducationDetails.add("Law");
		getEducationDetails.add("Post Graduate");
		getEducationDetails.add("vocational Education MBA");
		getEducationDetails.add("other");
		Collections.sort(getEducationDetails);
		return getEducationDetails;
	}

	public List<String> getGetEducation() {
		getEducation.add("B Arch");
		getEducation.add("B Ed");
		getEducation.add("B Pharm");
		getEducation.add("B Phil");
		getEducation.add("B Plan");
		getEducation.add("B Tech");
		getEducation.add("B.E");
		getEducation.add("B.TECH");
		getEducation.add("BA");
		getEducation.add("BAMS");
		getEducation.add("BBA");
		getEducation.add("BCA");
		getEducation.add("B. Com");
		getEducation.add("BDS");
		getEducation.add("BE");
		getEducation.add("BGL");
		getEducation.add("BHM");
		getEducation.add("BHMS");
		getEducation.add("BL");
		getEducation.add("B-Lib");
		getEducation.add("BPT");
		getEducation.add("BSC");
		getEducation.add("BVSc");
		getEducation.add("C.A.");
		getEducation.add("C.S.");
		getEducation.add("Class 1 to 12");
		getEducation.add("D.Ed");
		getEducation.add("Diploma");
		getEducation.add("high school");
		getEducation.add("HigherSecondary");
		getEducation.add("IAS");
		getEducation.add("ICWA");
		getEducation.add("IES");
		getEducation.add("IFS");
		getEducation.add("IPS");
		getEducation.add("IRS");
		getEducation.add("LLB");
		getEducation.add("LLM");
		getEducation.add("M Phil");
		getEducation.add("M Sc");
		getEducation.add("M Tech");
		getEducation.add("M. Arch.");
		getEducation.add("M. Com");
		getEducation.add("M. Ed.");
		getEducation.add("M. Pharm.");
		getEducation.add("MA");
		getEducation.add("MBA");
		getEducation.add("MBBS");
		getEducation.add("MCA");
		getEducation.add("MDS");
		getEducation.add("ME");
		getEducation.add("MHM");
		getEducation.add("ML");
		getEducation.add("M-Lib");
		getEducation.add("MPT");
		getEducation.add("MS (Engg.)");
		getEducation.add("Music");
		getEducation.add("MVSc");
		getEducation.add("NA");
		getEducation.add("Nil");
		getEducation.add("Other");
		getEducation.add("PGDCA");
		getEducation.add("PGDM");
		getEducation.add("PhD");
		Collections.sort(getEducation);
		return getEducation;
	}

	public List<String> getGetOccupation() {
		getOccupation.add("CEO / President, Director, Chairman");
		getOccupation.add("Accounts/Finance");
		getOccupation.add("Administrative");
		getOccupation.add("Advertising");
		getOccupation.add("Advocate");
		getOccupation.add("Chartered Accountant");
		getOccupation.add("Civil Services");
		getOccupation.add("Clerk");
		getOccupation.add("Air Hostess");
		getOccupation.add("Airforce");
		getOccupation.add("Airline");
		getOccupation.add("Architect");
		getOccupation.add("Army");
		getOccupation.add("Arts Craftsman");
		getOccupation.add("Company Secretary");
		getOccupation.add("Consultant");
		getOccupation.add("Customer Care Executive");
		getOccupation.add("Department of Electrical");
		getOccupation.add("Auditor");
		getOccupation.add("Banking Service");
		getOccupation.add("Beautician");
		getOccupation.add("Doctor");
		getOccupation.add("Business - kirana");
		getOccupation.add("Business-Contractor");
		getOccupation.add("Business- Spice");
		getOccupation.add("Business-Dried fruit");
		getOccupation.add("Business-Electrical goods");
		getOccupation.add("Entertainment");
		getOccupation.add("Business-Factory");
		getOccupation.add("Business-Fruit");
		getOccupation.add("Business-Gas dealer");
		getOccupation.add("Business-General Store");
		getOccupation.add("Business-Gold");
		getOccupation.add("Business-Grain");
		getOccupation.add("Business-Hardware");
		getOccupation.add("Business-Hotel");
		getOccupation.add("Business-Medical");
		getOccupation.add("Business-Metal");
		getOccupation.add("Business-Mobile/Phone");
		getOccupation.add("Business-Ice");
		getOccupation.add("Business-Electronic");
		getOccupation.add("Business-Invetr/battery");
		getOccupation.add("Business-Iron");
		getOccupation.add("Business-Oilseeds");
		getOccupation.add("Business-Paper/Book");
		getOccupation.add("Business-Plastic");
		getOccupation.add("Farming");
		getOccupation.add("Business-Printing");
		getOccupation.add("Business-Readymade garment");
		getOccupation.add("Business-Salt");
		getOccupation.add("Business-School/College");
		getOccupation.add("Business-Seasoning");
		getOccupation.add("Business-Software");
		getOccupation.add("Business-Sports equipment");
		getOccupation.add("Business-Steel");
		getOccupation.add("Fashion Designer");
		getOccupation.add("Hardware Professional");
		getOccupation.add("Business-Sweet-meat");
		getOccupation.add("Business-Tea");
		getOccupation.add("Business-Timber");
		getOccupation.add("Business-Vegetable");
		getOccupation.add("Business-Vehicle");
		getOccupation.add("Business-Alcohol");
		getOccupation.add("Business-Broker");
		getOccupation.add("Business-Bullion");
		getOccupation.add("Business-Cement");
		getOccupation.add("Business-Cloth");
		getOccupation.add("Business-Coaching");
		getOccupation.add("Business-Color/paint");
		getOccupation.add("Business-Real estate");
		getOccupation.add("Engineer");
		getOccupation.add("Engineer - Non IT");
		getOccupation.add("Event Management");
		getOccupation.add("Health Care");
		getOccupation.add("Hotel Management");
		getOccupation.add("Housewife");
		getOccupation.add("Insurance");
		getOccupation.add("Interior Designer");
		getOccupation.add("IT Industry");
		getOccupation.add("Journalist");
		getOccupation.add("Law Enforcement Officer");
		getOccupation.add("Lawyer Legal Professional");
		getOccupation.add("Lecturer");
		getOccupation.add("Manager");
		getOccupation.add("Marketing");
		getOccupation.add("Merchant Navy");
		getOccupation.add("Navy");
		getOccupation.add("Nil");
		getOccupation.add("Not Mention");
		getOccupation.add("Not Working");
		getOccupation.add("Nurse");
		getOccupation.add("Officer");
		getOccupation.add("Other");
		getOccupation.add("Paramedical");
		getOccupation.add("Pilot");
		getOccupation.add("Police Department");
		getOccupation.add("Private duty");
		getOccupation.add("Professor");
		getOccupation.add("Retired");
		getOccupation.add("Sales Executive");
		getOccupation.add("Scientist / Researcher");
		getOccupation.add("Social Worker");
		getOccupation.add("Software Professional");
		getOccupation.add("Sportsman");
		getOccupation.add("Study");
		getOccupation.add("Supervisor");
		getOccupation.add("Teaching");
		getOccupation.add("Technician");
		getOccupation.add("Telecommunication");
		getOccupation.add("Business - Grocery");
		getOccupation.add("Business-Farming");
		getOccupation.add("Business-Photo Studio");
		getOccupation.add("Business-Petrol Pump");
		getOccupation.add("Business-Food");
		getOccupation.add("Business-Automobile");
		Collections.sort(getOccupation);
		return getOccupation;
	}

	public List<String> getGetAgeRange() {
		getAgeRange.add("21 to 25 Years");
		getAgeRange.add("26 to 30 Years");
		getAgeRange.add("31 to 35 years");
		getAgeRange.add("36 to 40 Years");
		getAgeRange.add("40+ Years");

		return getAgeRange;
	}
}
