apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asatisamaj-matrimony
  name: asatisamaj-matrimony
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: asatisamaj-matrimony
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asatisamaj-matrimony
    spec:
      containers:
      - image: nitinasati/asatisamaj-matrimony-service:0.0.15-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: asatisamaj-matrimony
        envFrom:
          - configMapRef:
             name: asatisamaj-service
        readinessProbe: 
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe: 
          httpGet:
            port: 8000
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets: 
        - name: regcred 
      restartPolicy: Always
