apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asatisamaj-matrimony-web
  name: asatisamaj-matrimony-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: asatisamaj-matrimony-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asatisamaj-matrimony-web
    spec:
      containers:
      - image: nitinasati/asatisamaj-matrimony-web:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: asatisamaj-matrimony-web
        envFrom:
         - secretRef:
             name: asatisamaj-service-config
         - configMapRef:
             name: asatisamaj-matrimony-web-config
        readinessProbe: 
          httpGet:
            port: 8010
            path: /actuator/health/readiness
        livenessProbe: 
          httpGet:
            port: 8010
            path: /actuator/health/liveness
          initialDelaySeconds: 60
          periodSeconds: 10
      imagePullSecrets: 
        - name: regcred 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asatisamaj-matrimony-web
  name: asatisamaj-matrimony-web
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: asatisamaj-matrimony-web
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
    ASATISAMAJ_SERVICE_URI: http://asatisamaj-matrimony-svc
kind: ConfigMap
metadata:
  name: asatisamaj-matrimony-web-config
  namespace: default
