apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: nitinasati/mmv2-currency-conversion-service:0.0.13-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: currency-conversion
        envFrom:
         - configMapRef:
             name: currency-conversion
        readinessProbe: 
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe: 
          httpGet:
            port: 8100
            path: /actuator/health/liveness
      imagePullSecrets: 
        - name: regcred 
      restartPolicy: Always
      initialDelaySeconds: 10
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
    CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default
